# Generated by Django 5.0.3 on 2024-03-15 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0002_alter_customers_phone_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='phone_no',
            field=models.CharField(max_length=10),
        ),
    ]
